### ISSUE TITLE
Cannot use this code because of the restrictive license (I think this is a mistake)?

### ISSUE THREAD

**Issue by jonathantims** [wangzq/Azure-PowerShell-Extensions#1]
Dear wangzq,

I came to your repo by a message you posted on a forum inviting someone to download your scripts and use them.

However, neither I nor any other law abiding person can use your code because it has no explicit license -- and according to this GitHub page (https://help.github.com/articles/open-source-licensing/) the default license (where there is no explicit license) is "you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work."

Please could you add a license to the repo so that I can use your code -- it does exactly what I need and would be a great help.

**Comment by wangzq** [comment]
Added MIT license, thanks for reminding.

**Comment by jonathantims** [comment]
Thanks so much for quick turnaround! Bless you :)
